schema_version = "1.0.0"
id = "addon_reloader"
version = "1.1.1"
name = "Addon Reloader"
tagline = "Quick Reloading of Development Blender Add-ons"
maintainer = "letleon <letleon@163.com>"
type = "add-on"
website = "https://github.com/0xletleon/AddonReloader"
blender_version_min = "4.2.0"
tags = ["System", "Development"]
license = [
  "SPDX:GPL-3.0-or-later",
]
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/*.bat",
  "/*.jpg",
  "/*.png",
  "/.gitignore",
  "/*.md"
]